services:
  db:
    extends:
      file: docker-compose.yml
      service: db
    ports:
      - 5432:5432

  redis:
    extends:
      file: docker-compose.yml
      service: redis
    ports:
      - 6389:6379

  report:
    extends:
      file: docker-compose.yml
      service: report
    image: node:18.18.2
    working_dir: /usr/dev/src/services/report
    volumes:
      - .:/usr/dev
    command: "npm run dev"
    ports:
      - 9230:9229 # Debug port

  mail:
    extends:
      file: docker-compose.yml
      service: mail
    image: node:18.18.2
    working_dir: /usr/dev/src/services/mail
    volumes:
      - .:/usr/dev
    command: "npm run dev"
    ports:
      - 9231:9229 # Debug port

  maildev:
    image: maildev/maildev
    ports:
      - 1080:1080 # web interface
      - 1025:1025
    deploy:
      resources:
          limits:
            memory: 2G
    restart: unless-stopped
