include:
  - docker-compose.common.yml

services:
  ezreeport:
    build:
      target: aio
    volumes:
      - ./data/files-1/reports:/data/ezreeport/reports # Report output
      - ./data/files-1/db:/data/ezreeport/db # Files DB
    ports:
      - 8080:8080
    env_file:
      - .env
      - path: .env.local
        required: false
    extra_hosts:
      - host.docker.internal:host-gateway # Used because elastic is on the same machine, but not the same network
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: ${MEM_LIMIT:-7}G
    restart: unless-stopped
