services:
  db:
    extends:
      file: docker-compose.yml
      service: db
    ports:
      - 5432:5432

  redis:
    extends:
      file: docker-compose.yml
      service: redis
    ports:
      - 6389:6379

  api:
    extends:
      file: docker-compose.yml
      service: api
    image: node:20.11.0
    working_dir: /usr/dev/services/report
    volumes:
      - .:/usr/dev
    command: "npm run dev"
    ports:
      - 9230:9229 # Debug port

  mail:
    extends:
      file: docker-compose.yml
      service: mail
    image: node:20.11.0
    working_dir: /usr/dev/services/mail
    volumes:
      - .:/usr/dev
    command: "npm run dev"
    ports:
      - 9232:9229 # Debug port

  storybook:
    image: node:20.11.0
    working_dir: /usr/dev/services/vue
    volumes:
      - .:/usr/dev
    command: "npm run dev -- --no-open"
    ports:
      - 6006:6006
    restart: unless-stopped

  maildev:
    image: maildev/maildev
    ports:
      - 1080:1080 # web interface
      - 1025:1025
    deploy:
      resources:
          limits:
            memory: 2G
    restart: unless-stopped
