version: "3.8"

services:
  db:
    ports:
      - 5432:5432

  redis:
    ports:
      - 6389:6379

  report:
    image: node:18.13.0
    working_dir: /usr/src/report
    volumes:
      - ./src/services/report:/usr/src/report
    command: "npm run dev"
    ports:
      - 9230:9229 # Debug port

  mail:
    image: node:18.13.0
    working_dir: /usr/src/mail
    volumes:
      - ./src/services/mail:/usr/src/mail
    command: "npm run dev"
    ports:
      - 9231:9229 # Debug port

  maildev:
    image: maildev/maildev
    ports:
      - 1080:1080 # web interface
      - 1025:1025
    restart: unless-stopped
