version: "3.8"

services:
  db:
    image: postgres:15.0
    environment:
      - POSTGRES_USER=${DATABASE_USER:-postgres}
      - POSTGRES_DB=${DATABASE_USER:-postgres}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD:-changeme}
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    restart: unless-stopped

  redis:
    image: redis:7.0.5
    command: redis-server --save 60 1 --requirepass ${REDIS_PASSWORD:-changeme}
    volumes:
      - ./data/redis:/data
    ports:
      - 6389:6379
    restart: unless-stopped

  report:
    image: node:16.18.0
    working_dir: /report
    volumes:
      - ./src/report:/report
    command: "npm run dev"
    ports:
      - 8080:8080
      - 9230:9229 # Debug port
    depends_on:
      - db
      - redis
    restart: unless-stopped

  mail:
    image: node:16.18.0
    working_dir: /mail
    volumes:
      - ./src/mail:/mail
    command: "npm run dev"
    ports:
      - 8081:8080
      - 9231:9229 # Debug port
    environment:
      - REDIS_HOST
      - REDIS_PORT
      - REDIS_PASSWORD
      - DATABASE_PROTOCOL
      - DATABASE_USER
      - DATABASE_PASSWORD
      - DATABASE_HOST
      - DATABASE_PORT
      - DATABASE_DB
      - DATABASE_URL
      - LOG_LEVEL
    depends_on:
      - redis
    restart: unless-stopped
