version: "3.8"

services:
  db:
    ports:
      - 5432:5432
  
  redis:
    ports:
      - 6389:6379

  report:
    image: node:18.12.0
    working_dir: /report
    volumes:
      - ./src/services/report:/report
    command: "npm run dev"
    ports:
      - 9230:9229 # Debug port

  mail:
    image: node:18.12.0
    working_dir: /mail
    volumes:
      - ./src/services/mail:/mail
    command: "npm run dev"
    ports:
      - 9231:9229 # Debug port

  maildev:
    image: maildev/maildev
    ports:
      - 1080:1080 # web interface
      - 1025:1025
    restart: unless-stopped
