version: "3.8"

services:
  db:
    image: postgres:15.0
    environment:
      - POSTGRES_PASSWORD=changeme
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    restart: unless-stopped
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - 5050:80

  redis:
    image: redis:7.0.5
    command: redis-server --save 60 1 --requirepass ${EZMESURE_REDIS_PASSWORD:-changeme}
    volumes:
      - ./data/redis:/data
    ports:
      - 6389:6379
    restart: unless-stopped

  report:
    image: node:16.18.0
    working_dir: /report
    volumes:
      - ./src/report:/report
    command: "npm run dev"
    ports:
      - 8080:8080
      - 9230:9229 # Debug port
    environment:
      - REDIS_HOST
      - REDIS_PORT
      - REDIS_PASSWORD
      - LOG_LEVEL
      - ELASTIC_SCHEME
      - ELASTIC_HOST
      - ELASTIC_PORT
      - ELASTIC_API_KEY
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - db
      - redis
    restart: unless-stopped

  mail:
    image: node:16.18.0
    working_dir: /mail
    volumes:
      - ./src/mail:/mail
    command: "npm run dev"
    ports:
      - 8081:8080
      - 9231:9229 # Debug port
    depends_on:
      - redis
    # restart: unless-stopped
