packages:
  - 'packages/*'
  - 'services/*'

minimumReleaseAge: 1440

catalog:
  # deps
  typescript: ^7.0.2
  tsx: ^4.23.1 # Don't forget to update the aio stage in Dockerfile
  ofetch: ^2.0.0-alpha.3
  # dev deps
  '@types/node': ^24
  pino-pretty: ^13.0.0

catalogs:
  sdk:
    date-fns: ^4.1.0
    nanoid: ^5.1.5
    object-hash: ^3.0.0
    socket.io-client: ^4.8.1

allowBuilds:
  '@prisma/client': true
  '@prisma/engines': true
  better-sqlite3: true
  canvas: true
  core-js: false
  esbuild: false
  fastify-socket.io: false
  prisma: false
  sharp: false
