packages:
  - "services/common"

  - "services/report"
  - "services/worker"
  - "services/scheduler"
  - "services/mail"

  - "services/sdk"

  - "services/ezra"
  - "services/vue"

onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - canvas
