packages:
  - "packages/*"
  - "services/*"

onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - canvas

catalog:
  # deps
  typescript: ^5.6.2
  tsx: ^4.19.1
  # dev deps
  "@types/node": ^22.7.3
  pino-pretty: ^11.2.2