packages:
  - 'packages/*'
  - 'services/*'

onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - better-sqlite3
  - canvas

minimumReleaseAge: 1440

catalog:
  # deps
  typescript: ^5.8.3
  tsx: ^4.20.3 # Don't forget to update the aio stage in Dockerfile
  ofetch: ^2.0.0-alpha.3
  # dev deps
  '@types/node': ^24.0.10
  pino-pretty: ^13.0.0

catalogs:
  sdk:
    date-fns: ^4.1.0
    nanoid: ^5.1.5
    object-hash: ^3.0.0
    socket.io-client: ^4.8.1
