// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
export {};

declare module 'vue' {
  export interface GlobalComponents {
    ReportingTest: typeof import('./src/components/ReportingTest.vue')['default']
    'ReportingTest.story': typeof import('./src/components/ReportingTest.story.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VApp: typeof import('vuetify/lib')['VApp']
    VChip: typeof import('vuetify/lib')['VChip']
  }
}
