apm-server:
  host: "0.0.0.0:8200"
  # rum.enabled: true
  # ilm.setup:
  #   overwrite: true
  #   policies.name: "${MONITORING_INDEX_PREFIX}apm-rollover-30-days"

output.elasticsearch:
  hosts: "${ELASTIC_URL}"
  api_key: "${MONITORING_API_KEY}"
  ssl.verification_mode: "none"
  index: "${MONITORING_INDEX_PREFIX}apm-%{[observer.version]}-%{[processor.event]}-%{+yyyy.MM.dd}"

setup.template:
  name: "${MONITORING_INDEX_PREFIX}apm-server"
  pattern: "${MONITORING_INDEX_PREFIX}apm-*"

queue.mem.events: 4096

max_procs: 4