output.elasticsearch:
  hosts: "${ELASTIC_URL}"
  api_key: "${MONITORING_API_KEY}"
  ssl.verification_mode: "none"
  index: "${MONITORING_INDEX_PREFIX}metricbeat-%{[agent.version]}-%{+yyyy.MM.dd}"

setup:
  template:
    name: "${MONITORING_INDEX_PREFIX}metricbeat"
    pattern: "${MONITORING_INDEX_PREFIX}metricbeat-*"
  ilm:
    rollover_alias: "${MONITORING_INDEX_PREFIX}metricbeat-%{[agent.version]}"
    policy_name: "${MONITORING_INDEX_PREFIX}metricbeat"

metricbeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: false

metricbeat.modules:
  - module: postgresql
    period: 10s
    hosts: ["${DATABASE_PROTOCOL}://${DATABASE_USER}:${DATABASE_PASSWORD}@${DATABASE_HOST}:${DATABASE_PORT}/?sslmode=disable"]
    enabled: true

  - module: redis
    metricsets: ["info", "keyspace"]
    enabled: true
    period: 10s
    hosts: ["${REDIS_HOST}:${REDIS_PORT}"]
    password: ${REDIS_PASSWORD:changeme}

processors:
  - add_cloud_metadata: ~
