name: Build and Deploy SDK documentation

on:
  push:
    tags:
      - '@ezpaarse-project/ezreeport-sdk-js@*'

env:
  HUSKY: 0
  TURBO_UI: 'false'

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  build:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Setup pnpm ⚙️
        uses: pnpm/action-setup@v3

      - name: Setup Node ⚙️
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: 'pnpm'

      - name: Setup Pages ⚙️
        uses: actions/configure-pages@v5

      - name: Install dependencies ⚙️
        run: pnpm i --frozen-lockfile

      - name: Build documentation 🔧
        run: pnpm turbo run @ezpaarse-project/ezreeport-sdk-js#build:docs

      - name: Upload artifact 🚚
        uses: actions/upload-pages-artifact@v3
        with:
          path: services/sdk/docs

  deploy:
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy 🚀
        id: deployment
        uses: actions/deploy-pages@v4
